[숫자 야구 게임] 이진유 미션 제출합니다.
woowacourse-precourse/javascript-baseball pull request #216
Opened 2022-11-07 15:39 UTC by 22yuu

2022-11-09 12:09 UTC, cys4585 reviewed
JS에 대한 지식이 많다는게 느껴지는 코드입니다!
클래스를 잘 나누어서 활용하신 것 같아요. 다음 과제 진행에 큰 도움이 될 것 같습니다. ㅎㅎㅎ
다만 제가 아직 JS에 대한 지식이 부족해 좋은 리뷰를 해드리질 못한거 같아 아쉽네요 ㅜㅜ 
많이 배웠습니다 감사합니다. 😃 

혹시 시간이 있으시다면 제 코드도 리뷰 요청드립니다! 😄 
https://github.com/woowacourse-precourse/javascript-baseball/pull/45

2022-11-09 12:09 UTC, cys4585 commented on src/Game.js
> +  }
start 와 onInput을 따로 뒀어야 한 이유가 있으셨나요..? start가 onInput을 호출만 하기에 질문드립니다..! onInput가 별도로 사용되지도 않는 것 같구요

2022-11-09 12:09 UTC, cys4585 commented on src/Game.js
> +  isRestart(input) {
isRestart에서도 onGame처럼 예외처리를 Validation 객체에 맡겼으면 어땠을까요? ㅎㅎ

2022-11-09 12:09 UTC, cys4585 commented on src/Validation.js
> +  checkValidation(input) {
validation 처리 잘 배우고 갑니다...! 감사합니다 :)

2022-11-09 12:36 UTC, 22yuu commented on src/Game.js
> +  setTargetLength(length) {
네 맞습니다~! Game 로직을 숨길려는 의도도 있습니다. 그리고 Builder Pattern의 경우 생성자에 파라미터가 많은 경우에 유용하게 사용됩니다. 자세한 내용은 잘 정리된 블로그 링크 걸어드릴게요~!!

하나는 제가 따로 정리하고 있는 레포지토리이고 다른 링크는 설명이 대체적으로 설명이 잘되어 있는 것 같아서 첨부했어요!

* https://github.com/22yuu/TIL/blob/main/JavaScript/Builder%20Pattern.md
* https://dev-youngjun.tistory.com/197

2022-11-09 12:45 UTC, 22yuu commented on src/Game.js
> +  }
최대한 분리를 하다보니 그렇게된 것 같습니다...

목적은 상황(`처음 시작할 때`, `게임 진행 중 사용자에게 입력을 받을 때`, `게임이 끝났을 경우 재시작을 해야할 때` )에 따라 동적으로 callback함수를 불러와서 기능을 수행하려고 작성했었습니다. 

MissionUtils.Console.readLine()을 계속 작성하려면 손가락도 아프고 타입 실수가 잦아질 수 있기 때문에 Game 클래스 생성자에서 `this.io = MissionUtils.Console`을 선언하므로서 `this.io.readLine()`만 호출하면 되죠!

하지만 이것도 힘듭니다. 그리고 상황에 따라 사용자에게 동적으로 보여주며 코드를 줄일 방법을 고민하다가 탄생되게 저 코드이네요..

```javascript
const QuestionText = Object.freeze({
  startText: "숫자 야구 게임을 시작합니다.",
  inputText: "숫자를 입력해주세요 : ",
  endText: "3개의 숫자를 모두 맞히셨습니다! 게임 종료",
  redoText: "게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요.",
});

// 처음 시작할 때, 게임 진행 중 사용자로부터 입력을 받을 때
this.start(QuestionText.startText, onGame);

// 게임이 끝나 재시작을 물어볼 경우
this.start(QuestionText.endText, isRestart);

```

장황하게 설명을 하긴 했는데... 잘 이해가 되셨을지.. ㅠㅠ

2022-11-09 12:47 UTC, 22yuu commented on src/ErrorMsg.js
> +});
저도 1주차 때 피어리뷰를 통해 Object.freeze()에 대해 배웠어요 ㅎㅎ ide의 코드어시스턴트를 이용해 dot 연산자(.)를 사용하면 선언된 객체들을 보여주기 때문에 개발자들의 타이핑 실수를 방지하기 위해서 많이 사용한다고 합니다. 기존 Object.freeze()의 경우 객체 보호를 위해 많이 사용한다고 해요!

* https://github.com/22yuu/TIL/blob/main/JavaScript/%EA%B0%9D%EC%B2%B4%20%EB%8F%99%EA%B2%B0.md

2022-11-09 12:54 UTC, 22yuu commented on src/Game.js
> +  isRestart(input) {
맞아요 이거 고민을 했었는데..

 onGame의 input은 사용자의 입력값인 `1~9 서로 다른 수의 3자리`에 반해 재시작의 경우 `1`, `2`의 입력값만 받기 때문에 입력값의 성격이 다르다(?)라고 생각이 들어서 사용자 input에 대한 유효성검사, 재시작 입력에 대한 유효성 검사를 따로 둘까 하다가 재시작의 경우 `1`, `2`의 값 외 다른 값이 들어오면 예외 처리시키면 되겠다싶어서 따로 만들지 않았어요~

이 코드의 Validation의 경우 사용자 input 값에 대한 유효성 검사를 하는 기능으로 남겨두고 싶었어요!

2022-11-09 13:24 UTC, 22yuu commented on src/Validation.js
> +  checkValidation(input) {
배워가실게 있다니! 정말 기쁩니다 😊

2022-11-09 14:35 UTC, Gilpop8663 reviewed
2주차 미션 코드 구현하신 것 보고 많이 배운 것 같습니다. 잘 보고 갑니다!

2022-11-09 14:35 UTC, Gilpop8663 commented on src/Game.js
> +  setTargetLength(length) {
@22yuu  덕분에 Builder Pattern에 대해 알게 되었습니다 ! 알려주셔서 감사합니다

2022-11-09 14:35 UTC, Gilpop8663 commented on src/ErrorMsg.js
> +});
덕분에 Object freeze에 대해 알게 되었습니다. 다만 Object.freeze를 사용하여 상수를 관리할 때 몇 개는 소문자, 몇 개는 대문자인 부분을 앞의 문자는 전부 소문자로 시작하는 것이 어떨까요?  아니면 의도하신 부분이 있는 지 궁금합니다!  <a href="https://github.com/airbnb/javascript#naming--uppercase">airbnb 컨벤션 가이드 23.10</a>

2022-11-12 06:11 UTC, kimyou1102 commented
제가 놓친 부분들을 피드백 해주셔서 저도 유의미한 피드백을 드리고 싶었는데 제가 오히려 배워만 가네요.... 최대한 기능별로 분리해서 만드신 것도 그렇고 제가 익숙지 않아 어렵게 느꼈던 클래스 분리도 많이 배웠습니다 감사합니다🙂🙂

2022-11-12 07:32 UTC, kimyou1102 requested changes
제가 놓친 부분들을 피드백 해주셔서 저도 유의미한 피드백을 드리고 싶었는데 제가 오히려 배워만 가네요.... 최대한 기능별로 분리해서 만드신 것도 그렇고 제가 익숙지 않아 어렵게 느꼈던 클래스 분리도 많이 배웠습니다 감사합니다🙂🙂

2022-11-12 15:26 UTC, 22yuu commented on src/Game.js
> +  inputToArray(input) {
입력값을 배열로 변환하기 위한 함수입니다~ `split("")`을 이용해서 배열로 변환해도 되지만 String 관련 메서드는 성능에 좋지 않은 영향을 끼치는 것으로 알고 있어 할 수 있는한 수학 수식을 최대한 활용해 코드를 작성해봤습니다. 

정수 값으로 변환된 input값을 10을 나눈 나머지를 배열에 넣어줍니다. `ex) 123 % 10 = 3`

그리고 나서 10을 나누고 나머지는 버려주는 것이죠 `123 / 10 = 12` 이 과정을 되풀이하면 `123`은 `3,2,1`로 분리해서 배열로 넣어줬습니다. push를 사용하게 되면 [3,2,1]로 값이 할당되어 unshift를 이용해 [1,2,3] 순서대로 할당될 수 있게 했어요.

2022-11-14 02:35 UTC, kimyou1102 commented on src/Game.js
> +  inputToArray(input) {
아 당연하게 split만 생각했는데 수학적으로 분리하는 방법도 있겠네요!! 답변 감사합니다😀

2023-08-31 05:45 UTC, closed without merging